---
- name: Installing and Configuring Web Server on target node
  # Hosts Section
  hosts:
  - target3
  become: yes
  # Variable Section
  vars:
    http_port: 8080
    nginx_package_url: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-{{ansible_distribution_major_version}}-0.el{{ansible_distribution_major_version}}.ngx.noarch.rpm
    node_ip: 192.168.0.3
    greeting: 'Ansible is awesome!'
  # Tasks Section
  tasks:
  - name: Debugging NGINX_PACKAGE_URL using msg
    debug:
      msg: "Nginx RPM Package - {{ nginx_package_url }}"

  - name: Debugging NGINX_PACKAGE_URL using var
    debug:
      var: nginx_package_url

  - name: Installing Apache Web Server
    yum:
      update_cache: yes
      name:
      - httpd
      - libsemanage-python
      state: latest

  - name: Using Jinja2 template to put index.html file
    template:
      src: index.j2
      dest: /var/www/html/index.html