---
- name: Deploy Ansible User
  hosts: target1
  tasks:
    - name: Create Devops User
      user:
        name: osboxes
        groups: "{{ admin_group }}"
        append: true
        create_home: true
        comment: 'Ansible Management Account'
        expires: -1
        password: '$6$AZ$tfbOH9FsYkG9EkUfU6Ms7qvQM7Jlv5hbWlfaZ4BLkUFUPWalAFW12L3cioXyrWMkmNAyjxC9tCMBiTubILv3F/'

    - name: Deploy Local User SSH Key
      authorized_key:
        user: devops
        state: present
        manage_dir: true
        key: "{{ lookup('file', '/home/osboxes/.ssh/id_rsa.pub') }}"

    - name: Setup Sudo Access for Devops User
      copy:
        dest: /etc/sudoers.d/devops
        content: 'devops ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s