---
- hosts: "target1"
  connection: "local"
  vars:
    users:
      - tharmeka
      - nandhu
  tasks:
    - name: "Create user accounts and add users to groups"
      user:
        name: "{{ item }}" state=present
        group: admin
      with_items: "{{ users }}"