---
- name: Deploy Ansible User
  hosts: target1
  tasks:
    - name: Create User
      user:
        name: devops
        groups: "{{ admin_group }}"
        create_home: true
        comment: 'Ansible Management Account'
        expires: -1
        password:
    - name: Install SSH Key
      authorized_key:
         user: devops
         state: present
         manage_dir: true
         key: "{{ lookup('file', '/home/osboxes/.ssh/id_rsa.pub') }}"

    - name: Setup Devops Sudo Access
      copy:
         dest: /etc/sudoers.d/devops
         content: 'devops ALL=(ALL) NOPASSWD: ALL'
         validate: /usr/sbin/visudo -cf %s