---
- name:  Create New Users
  hosts: target1
  gather_facts: false
  tasks:
    - name: Create Users Task
      user:
        name: "{{ item }}"
        state: present
        password: " {{ default_user_password | password_hash('sha512', 'A512) }}"
        shell: /bin/bash
        group: "{{ admin_group }}"
      loop:
        - bob
        - wendy
        - lofty
        - dizzy