---
- name:  Create Users & Groups
  hosts: target1
  gather_facts: false
  tasks:
    - name: Create Users Task
      user:
        name: palani
        state: present
        password: "{{ 'password' | password_hash('sha512','A512') }}"
        shell: /bin/bash
        group: "{{ admin_group }}"