---
- name:  Clean  Users Accounts
  hosts: target1
  gather_facts: false
  tasks:
    - name: Delete Users
      user:
        name: "{{ item }}"
        state: absent
        remove: true



      loop:
        - bob
        - wendy
        - lofty
        - dizzy